baseURL = 'https://declanquinnnn.github.io/'
languageCode = 'en-us'
title = '_my website'
theme = 'typo'

enableEmoji = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[module]
[module.hugoVersion]
extended = false
min = "0.116.0"

# Default config
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "home"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "A place for some thoughts"

# Appearance settings
theme = 'light'
colorPalette = 'default'
hideHeader = false
singleDateFormat = '2006-01-02'

# Intro on main page, content is markdown
homeIntroTitle = 'hello there!'
homeIntroContent = """
Trying to figure stuff out, and hoping this place can encourage me to create and learn more and better-er.
"""

# Collection to display on home
homeCollectionTitle = "here's some posts :)"
homeCollection = 'posts'

toc = false
showFooter = true
footerContent = """
Copyright © 2025 Declan Quinn.
"""

# Lists parameters
paginationSize = 100
listSummaries = false
listDateFormat = '2006-01-02'

# [[params.social]]
# name = "github"
# url = "https://github.com/declanquinnnn"

# Main menu pages
[[params.menu]]
name = "home"
url = ""
weight=10

[[params.menu]]
name = "posts"
url = "posts"
weight=20

[[params.menu]]
name = "about"
url = "about"
weight=30

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

